Repository quantum9Innovation/QuasarOS, pull requests merged in 2025-01, with the labels that each got.

#17 fix(boot): update `pkiBundle` location
  modules/lanzaboote.nix
Labels: bug, critical

#18 fix(time): correct updateTimezone service
  configuration.nix
Labels: bug, services

#19 Use flake.nix to track aquamarine so hash doesn't have to be specified
  configuration.nix
  flake.nix
Labels: refactor, inputs

#20 fix aquamarine error causing critical sleep failure
  configuration.nix
  flake.lock
  flake.nix
Labels: bug, refactor, inputs, critical

#21 feat(hardware): support logitech peripherals
  configuration.nix
Labels: services, hardware

#24 Stylix
  configuration.nix
  flake.lock
  flake.nix
  home.nix
  modules/hyprland.nix
  modules/waybar.css
  walls/default.jpg
Labels: enhancement, refactor, inputs, services, rices, pkg

#25 feat(hardware): support logitech peripherals (#21)
  configuration.nix
Labels: enhancement, hardware
